%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Mono"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Mono"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 873.0
Camera1.fy: 872.0
Camera1.cx: 480.0
Camera1.cy: 270.0

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera.width: 960
Camera.height: 540

Camera.newWidth: 960
Camera.newHeight: 540

# Camera frames per second 
Camera.fps: 10

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1


# # Transformation from camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [  0.,  0.,  -1.,  0.,
            1.,  0.,  0.,   0.,
            0.,  -1.,  0.,  0.,
            0.,  0.,  0.,  1.]


# IMU noise
## real
# IMU.NoiseGyro: 0.0012472147671797335      # rad / s ^0.5
# IMU.NoiseAcc: 0.003738984379199222     # m / s ^1.5
# IMU.GyroWalk: 7.031995993759694e-06  # rad / s ^1.5
# IMU.AccWalk: 4.928157185122543e-05    # m / s ^2.5
# IMU.Frequency: 1000.0      # s ^ -1

IMU.NoiseGyro: 1.6968e-04      # rad / s ^0.5
IMU.NoiseAcc: 2.0000e-3     # m / s ^1.5
IMU.GyroWalk: 1.9393e-05  # rad / s ^1.5
IMU.AccWalk: 3.0000e-03    # m / s ^2.5
IMU.Frequency: 100.0      # s ^ -1
#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 12

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
# ORBextractor.iniThFAST: 20
# ORBextractor.minThFAST: 7

ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7


#--------------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

